name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: ⬇️ Checkout Code
          uses: actions/checkout@v4

        - name: 🐢 Setup Node
          uses: actions/setup-node@v4
          with:
            node-version-file: '.nvmrc'

        - name: 🏗️ Install Dependencies
          run: npm install
        - name: ⚙️ Typecheck
          run: npm run typecheck

        - name: 🔍 Lint
          run: npm run lint

        - name: 🧪 Run tests and generate Allure
          run: npm run test:local:allure

        - name: 📁 Upload Allure report
          uses: actions/upload-artifact@v4
          if: always()
          with:
            name: allure-report
            path: allure-report

        - name: 📦 Upload Logs (on failure)
          uses: actions/upload-artifact@v4
          if: failure()
          with:
            name: logs
            path: logs

